[2023-07-08 01:02:25,605] {processor.py:153} INFO - Started process (PID=35864) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:02:25,606] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:02:25,607] {logging_mixin.py:115} INFO - [2023-07-08 01:02:25,607] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:02:25,636] {logging_mixin.py:115} INFO - [2023-07-08 01:02:25,635] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:02:25,637] {logging_mixin.py:115} INFO - [2023-07-08 01:02:25,636] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:02:25,637] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:02:25,653] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2023-07-08 01:03:07,066] {processor.py:153} INFO - Started process (PID=36293) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:07,070] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:03:07,072] {logging_mixin.py:115} INFO - [2023-07-08 01:03:07,072] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:07,106] {logging_mixin.py:115} INFO - [2023-07-08 01:03:07,106] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:03:07,107] {logging_mixin.py:115} INFO - [2023-07-08 01:03:07,107] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:03:07,107] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:07,128] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2023-07-08 01:03:46,300] {processor.py:153} INFO - Started process (PID=36548) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:46,304] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:03:46,306] {logging_mixin.py:115} INFO - [2023-07-08 01:03:46,306] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:46,348] {logging_mixin.py:115} INFO - [2023-07-08 01:03:46,347] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:03:46,348] {logging_mixin.py:115} INFO - [2023-07-08 01:03:46,348] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:03:46,348] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:03:46,375] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2023-07-08 01:04:25,563] {processor.py:153} INFO - Started process (PID=36930) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:04:25,564] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:04:25,565] {logging_mixin.py:115} INFO - [2023-07-08 01:04:25,565] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:04:25,595] {logging_mixin.py:115} INFO - [2023-07-08 01:04:25,595] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:04:25,596] {logging_mixin.py:115} INFO - [2023-07-08 01:04:25,595] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:04:25,596] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:04:25,614] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.056 seconds
[2023-07-08 01:05:32,636] {processor.py:153} INFO - Started process (PID=37923) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:05:32,637] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:05:32,637] {logging_mixin.py:115} INFO - [2023-07-08 01:05:32,637] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:05:32,652] {logging_mixin.py:115} INFO - [2023-07-08 01:05:32,651] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:05:32,652] {logging_mixin.py:115} INFO - [2023-07-08 01:05:32,652] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:05:32,652] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:05:32,661] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2023-07-08 01:06:48,332] {processor.py:153} INFO - Started process (PID=38639) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:06:48,336] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:06:48,337] {logging_mixin.py:115} INFO - [2023-07-08 01:06:48,337] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:06:48,370] {logging_mixin.py:115} INFO - [2023-07-08 01:06:48,369] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:06:48,370] {logging_mixin.py:115} INFO - [2023-07-08 01:06:48,370] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:06:48,371] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:06:48,390] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 01:07:27,969] {processor.py:153} INFO - Started process (PID=38888) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:07:27,970] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:07:27,971] {logging_mixin.py:115} INFO - [2023-07-08 01:07:27,971] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:07:28,005] {logging_mixin.py:115} INFO - [2023-07-08 01:07:28,004] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:07:28,005] {logging_mixin.py:115} INFO - [2023-07-08 01:07:28,005] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:07:28,005] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:07:28,028] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 01:08:07,046] {processor.py:153} INFO - Started process (PID=38957) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:07,050] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:08:07,051] {logging_mixin.py:115} INFO - [2023-07-08 01:08:07,051] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:07,084] {logging_mixin.py:115} INFO - [2023-07-08 01:08:07,083] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:08:07,084] {logging_mixin.py:115} INFO - [2023-07-08 01:08:07,084] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:08:07,085] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:07,104] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 01:08:46,575] {processor.py:153} INFO - Started process (PID=39038) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:46,578] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:08:46,579] {logging_mixin.py:115} INFO - [2023-07-08 01:08:46,579] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:46,612] {logging_mixin.py:115} INFO - [2023-07-08 01:08:46,611] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:08:46,613] {logging_mixin.py:115} INFO - [2023-07-08 01:08:46,612] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:08:46,613] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:08:46,632] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 01:09:26,373] {processor.py:153} INFO - Started process (PID=39111) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:09:26,375] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:09:26,376] {logging_mixin.py:115} INFO - [2023-07-08 01:09:26,375] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:09:26,409] {logging_mixin.py:115} INFO - [2023-07-08 01:09:26,408] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:09:26,409] {logging_mixin.py:115} INFO - [2023-07-08 01:09:26,409] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:09:26,409] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:09:26,429] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 01:10:06,372] {processor.py:153} INFO - Started process (PID=39201) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:06,376] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:10:06,377] {logging_mixin.py:115} INFO - [2023-07-08 01:10:06,377] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:06,410] {logging_mixin.py:115} INFO - [2023-07-08 01:10:06,409] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:10:06,410] {logging_mixin.py:115} INFO - [2023-07-08 01:10:06,410] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:10:06,411] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:06,430] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 01:10:43,800] {processor.py:153} INFO - Started process (PID=39362) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:43,801] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:10:43,802] {logging_mixin.py:115} INFO - [2023-07-08 01:10:43,802] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:43,835] {logging_mixin.py:115} INFO - [2023-07-08 01:10:43,834] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:10:43,836] {logging_mixin.py:115} INFO - [2023-07-08 01:10:43,836] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:10:43,836] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:10:43,857] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 01:11:28,244] {processor.py:153} INFO - Started process (PID=39692) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:11:28,248] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:11:28,249] {logging_mixin.py:115} INFO - [2023-07-08 01:11:28,249] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:11:28,283] {logging_mixin.py:115} INFO - [2023-07-08 01:11:28,282] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:11:28,283] {logging_mixin.py:115} INFO - [2023-07-08 01:11:28,283] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:11:28,284] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:11:28,304] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 01:12:07,576] {processor.py:153} INFO - Started process (PID=39825) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:07,580] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:12:07,581] {logging_mixin.py:115} INFO - [2023-07-08 01:12:07,581] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:07,616] {logging_mixin.py:115} INFO - [2023-07-08 01:12:07,616] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:12:07,617] {logging_mixin.py:115} INFO - [2023-07-08 01:12:07,617] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:12:07,617] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:07,638] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2023-07-08 01:12:47,545] {processor.py:153} INFO - Started process (PID=39987) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:47,546] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:12:47,547] {logging_mixin.py:115} INFO - [2023-07-08 01:12:47,547] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:47,582] {logging_mixin.py:115} INFO - [2023-07-08 01:12:47,581] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:12:47,582] {logging_mixin.py:115} INFO - [2023-07-08 01:12:47,582] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:12:47,583] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:12:47,603] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 01:13:27,921] {processor.py:153} INFO - Started process (PID=40077) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:13:27,925] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:13:27,926] {logging_mixin.py:115} INFO - [2023-07-08 01:13:27,926] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:13:27,961] {logging_mixin.py:115} INFO - [2023-07-08 01:13:27,960] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:13:27,961] {logging_mixin.py:115} INFO - [2023-07-08 01:13:27,961] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:13:27,961] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:13:27,983] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2023-07-08 01:14:06,862] {processor.py:153} INFO - Started process (PID=40161) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:06,870] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:14:06,871] {logging_mixin.py:115} INFO - [2023-07-08 01:14:06,871] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:06,905] {logging_mixin.py:115} INFO - [2023-07-08 01:14:06,904] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:14:06,905] {logging_mixin.py:115} INFO - [2023-07-08 01:14:06,905] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:14:06,905] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:06,925] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2023-07-08 01:14:46,953] {processor.py:153} INFO - Started process (PID=40349) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:46,955] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:14:46,956] {logging_mixin.py:115} INFO - [2023-07-08 01:14:46,956] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:46,990] {logging_mixin.py:115} INFO - [2023-07-08 01:14:46,989] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:14:46,990] {logging_mixin.py:115} INFO - [2023-07-08 01:14:46,990] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:14:46,990] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:14:47,010] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 01:15:24,865] {processor.py:153} INFO - Started process (PID=40508) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:15:24,869] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:15:24,870] {logging_mixin.py:115} INFO - [2023-07-08 01:15:24,870] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:15:24,907] {logging_mixin.py:115} INFO - [2023-07-08 01:15:24,907] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:15:24,908] {logging_mixin.py:115} INFO - [2023-07-08 01:15:24,908] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:15:24,908] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:15:24,930] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2023-07-08 01:16:29,435] {processor.py:153} INFO - Started process (PID=40967) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:16:29,437] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:16:29,438] {logging_mixin.py:115} INFO - [2023-07-08 01:16:29,437] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:16:29,474] {logging_mixin.py:115} INFO - [2023-07-08 01:16:29,473] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:16:29,475] {logging_mixin.py:115} INFO - [2023-07-08 01:16:29,475] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:16:29,475] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:16:29,494] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2023-07-08 01:18:00,325] {processor.py:153} INFO - Started process (PID=41351) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:00,329] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:18:00,330] {logging_mixin.py:115} INFO - [2023-07-08 01:18:00,330] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:00,366] {logging_mixin.py:115} INFO - [2023-07-08 01:18:00,365] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:18:00,366] {logging_mixin.py:115} INFO - [2023-07-08 01:18:00,366] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:18:00,366] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:00,386] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2023-07-08 01:18:38,805] {processor.py:153} INFO - Started process (PID=41452) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:38,809] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:18:38,810] {logging_mixin.py:115} INFO - [2023-07-08 01:18:38,810] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:38,845] {logging_mixin.py:115} INFO - [2023-07-08 01:18:38,844] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:18:38,846] {logging_mixin.py:115} INFO - [2023-07-08 01:18:38,845] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:18:38,846] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:18:38,872] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2023-07-08 01:19:16,686] {processor.py:153} INFO - Started process (PID=41546) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:16,690] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:19:16,691] {logging_mixin.py:115} INFO - [2023-07-08 01:19:16,691] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:16,726] {logging_mixin.py:115} INFO - [2023-07-08 01:19:16,726] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:19:16,727] {logging_mixin.py:115} INFO - [2023-07-08 01:19:16,727] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:19:16,727] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:16,747] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2023-07-08 01:19:53,094] {processor.py:153} INFO - Started process (PID=41605) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:53,098] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 01:19:53,100] {logging_mixin.py:115} INFO - [2023-07-08 01:19:53,099] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:53,136] {logging_mixin.py:115} INFO - [2023-07-08 01:19:53,135] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 01:19:53,136] {logging_mixin.py:115} INFO - [2023-07-08 01:19:53,136] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 01:19:53,137] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 01:19:53,157] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2023-07-08 10:16:25,299] {processor.py:153} INFO - Started process (PID=4683) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:16:25,300] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:16:25,302] {logging_mixin.py:115} INFO - [2023-07-08 10:16:25,301] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:16:25,335] {logging_mixin.py:115} INFO - [2023-07-08 10:16:25,334] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:16:25,336] {logging_mixin.py:115} INFO - [2023-07-08 10:16:25,336] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:16:25,336] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:16:25,356] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 10:17:03,244] {processor.py:153} INFO - Started process (PID=5126) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:03,245] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:17:03,246] {logging_mixin.py:115} INFO - [2023-07-08 10:17:03,246] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:03,279] {logging_mixin.py:115} INFO - [2023-07-08 10:17:03,278] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:17:03,279] {logging_mixin.py:115} INFO - [2023-07-08 10:17:03,279] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:17:03,280] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:03,299] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2023-07-08 10:17:39,267] {processor.py:153} INFO - Started process (PID=5521) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:39,271] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:17:39,272] {logging_mixin.py:115} INFO - [2023-07-08 10:17:39,272] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:39,306] {logging_mixin.py:115} INFO - [2023-07-08 10:17:39,305] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:17:39,306] {logging_mixin.py:115} INFO - [2023-07-08 10:17:39,306] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:17:39,306] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:17:39,326] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:18:16,779] {processor.py:153} INFO - Started process (PID=5592) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:16,783] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:18:16,784] {logging_mixin.py:115} INFO - [2023-07-08 10:18:16,784] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:16,817] {logging_mixin.py:115} INFO - [2023-07-08 10:18:16,816] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:18:16,817] {logging_mixin.py:115} INFO - [2023-07-08 10:18:16,817] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:18:16,818] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:16,837] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:18:55,387] {processor.py:153} INFO - Started process (PID=5673) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:55,390] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:18:55,391] {logging_mixin.py:115} INFO - [2023-07-08 10:18:55,391] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:55,424] {logging_mixin.py:115} INFO - [2023-07-08 10:18:55,424] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:18:55,425] {logging_mixin.py:115} INFO - [2023-07-08 10:18:55,425] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:18:55,425] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:18:55,445] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:19:33,410] {processor.py:153} INFO - Started process (PID=5742) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:19:33,412] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:19:33,413] {logging_mixin.py:115} INFO - [2023-07-08 10:19:33,413] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:19:33,446] {logging_mixin.py:115} INFO - [2023-07-08 10:19:33,445] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:19:33,446] {logging_mixin.py:115} INFO - [2023-07-08 10:19:33,446] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:19:33,447] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:19:33,466] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 10:20:11,511] {processor.py:153} INFO - Started process (PID=5805) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:11,515] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:20:11,516] {logging_mixin.py:115} INFO - [2023-07-08 10:20:11,516] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:11,549] {logging_mixin.py:115} INFO - [2023-07-08 10:20:11,548] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:20:11,550] {logging_mixin.py:115} INFO - [2023-07-08 10:20:11,549] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:20:11,550] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:11,570] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:20:51,373] {processor.py:153} INFO - Started process (PID=5875) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:51,374] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:20:51,376] {logging_mixin.py:115} INFO - [2023-07-08 10:20:51,376] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:51,408] {logging_mixin.py:115} INFO - [2023-07-08 10:20:51,408] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:20:51,409] {logging_mixin.py:115} INFO - [2023-07-08 10:20:51,409] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:20:51,409] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:20:51,430] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 10:21:31,511] {processor.py:153} INFO - Started process (PID=6001) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:21:31,513] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:21:31,515] {logging_mixin.py:115} INFO - [2023-07-08 10:21:31,514] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:21:31,549] {logging_mixin.py:115} INFO - [2023-07-08 10:21:31,549] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:21:31,550] {logging_mixin.py:115} INFO - [2023-07-08 10:21:31,550] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:21:31,550] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:21:31,570] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:22:08,760] {processor.py:153} INFO - Started process (PID=6061) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:08,764] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:22:08,765] {logging_mixin.py:115} INFO - [2023-07-08 10:22:08,765] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:08,801] {logging_mixin.py:115} INFO - [2023-07-08 10:22:08,800] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:22:08,801] {logging_mixin.py:115} INFO - [2023-07-08 10:22:08,801] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:22:08,801] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:08,821] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2023-07-08 10:22:47,097] {processor.py:153} INFO - Started process (PID=6152) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:47,101] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:22:47,102] {logging_mixin.py:115} INFO - [2023-07-08 10:22:47,102] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:47,135] {logging_mixin.py:115} INFO - [2023-07-08 10:22:47,134] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:22:47,135] {logging_mixin.py:115} INFO - [2023-07-08 10:22:47,135] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:22:47,136] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:22:47,155] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 10:23:26,270] {processor.py:153} INFO - Started process (PID=6221) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:23:26,274] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:23:26,275] {logging_mixin.py:115} INFO - [2023-07-08 10:23:26,275] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:23:26,309] {logging_mixin.py:115} INFO - [2023-07-08 10:23:26,308] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:23:26,309] {logging_mixin.py:115} INFO - [2023-07-08 10:23:26,309] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:23:26,309] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:23:26,329] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:24:05,335] {processor.py:153} INFO - Started process (PID=6293) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:05,339] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:24:05,340] {logging_mixin.py:115} INFO - [2023-07-08 10:24:05,340] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:05,374] {logging_mixin.py:115} INFO - [2023-07-08 10:24:05,373] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:24:05,374] {logging_mixin.py:115} INFO - [2023-07-08 10:24:05,374] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:24:05,374] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:05,394] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:24:43,421] {processor.py:153} INFO - Started process (PID=6366) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:43,424] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:24:43,425] {logging_mixin.py:115} INFO - [2023-07-08 10:24:43,425] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:43,459] {logging_mixin.py:115} INFO - [2023-07-08 10:24:43,458] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:24:43,459] {logging_mixin.py:115} INFO - [2023-07-08 10:24:43,459] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:24:43,459] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:24:43,479] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:25:19,914] {processor.py:153} INFO - Started process (PID=6430) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:19,918] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:25:19,919] {logging_mixin.py:115} INFO - [2023-07-08 10:25:19,918] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:19,952] {logging_mixin.py:115} INFO - [2023-07-08 10:25:19,951] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:25:19,952] {logging_mixin.py:115} INFO - [2023-07-08 10:25:19,952] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:25:19,952] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:19,972] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:25:57,919] {processor.py:153} INFO - Started process (PID=6501) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:57,924] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:25:57,925] {logging_mixin.py:115} INFO - [2023-07-08 10:25:57,925] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:57,958] {logging_mixin.py:115} INFO - [2023-07-08 10:25:57,958] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:25:57,959] {logging_mixin.py:115} INFO - [2023-07-08 10:25:57,959] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:25:57,959] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:25:57,979] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2023-07-08 10:26:35,619] {processor.py:153} INFO - Started process (PID=6621) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:26:35,623] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:26:35,624] {logging_mixin.py:115} INFO - [2023-07-08 10:26:35,624] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:26:35,658] {logging_mixin.py:115} INFO - [2023-07-08 10:26:35,658] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:26:35,659] {logging_mixin.py:115} INFO - [2023-07-08 10:26:35,659] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:26:35,659] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:26:35,679] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 10:27:17,331] {processor.py:153} INFO - Started process (PID=6691) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:17,335] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:27:17,336] {logging_mixin.py:115} INFO - [2023-07-08 10:27:17,336] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:17,370] {logging_mixin.py:115} INFO - [2023-07-08 10:27:17,369] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:27:17,370] {logging_mixin.py:115} INFO - [2023-07-08 10:27:17,370] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:27:17,370] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:17,390] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:27:50,538] {processor.py:153} INFO - Started process (PID=6778) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:50,542] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:27:50,543] {logging_mixin.py:115} INFO - [2023-07-08 10:27:50,542] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:50,576] {logging_mixin.py:115} INFO - [2023-07-08 10:27:50,576] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:27:50,577] {logging_mixin.py:115} INFO - [2023-07-08 10:27:50,577] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:27:50,577] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:27:50,596] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:28:27,230] {processor.py:153} INFO - Started process (PID=6850) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:28:27,234] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:28:27,235] {logging_mixin.py:115} INFO - [2023-07-08 10:28:27,235] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:28:27,269] {logging_mixin.py:115} INFO - [2023-07-08 10:28:27,268] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:28:27,269] {logging_mixin.py:115} INFO - [2023-07-08 10:28:27,269] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:28:27,269] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:28:27,288] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:29:02,581] {processor.py:153} INFO - Started process (PID=6918) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:02,585] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:29:02,586] {logging_mixin.py:115} INFO - [2023-07-08 10:29:02,586] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:02,620] {logging_mixin.py:115} INFO - [2023-07-08 10:29:02,619] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:29:02,620] {logging_mixin.py:115} INFO - [2023-07-08 10:29:02,620] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:29:02,620] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:02,639] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:29:39,070] {processor.py:153} INFO - Started process (PID=6990) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:39,072] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:29:39,073] {logging_mixin.py:115} INFO - [2023-07-08 10:29:39,073] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:39,123] {logging_mixin.py:115} INFO - [2023-07-08 10:29:39,122] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:29:39,123] {logging_mixin.py:115} INFO - [2023-07-08 10:29:39,123] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:29:39,124] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:29:39,148] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.086 seconds
[2023-07-08 10:30:16,979] {processor.py:153} INFO - Started process (PID=7055) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:16,983] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:30:16,984] {logging_mixin.py:115} INFO - [2023-07-08 10:30:16,984] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:17,018] {logging_mixin.py:115} INFO - [2023-07-08 10:30:17,017] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:30:17,018] {logging_mixin.py:115} INFO - [2023-07-08 10:30:17,018] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:30:17,019] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:17,038] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 10:30:57,500] {processor.py:153} INFO - Started process (PID=7128) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:57,504] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 10:30:57,505] {logging_mixin.py:115} INFO - [2023-07-08 10:30:57,504] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:57,538] {logging_mixin.py:115} INFO - [2023-07-08 10:30:57,537] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 10:30:57,539] {logging_mixin.py:115} INFO - [2023-07-08 10:30:57,538] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 10:30:57,539] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 10:30:57,558] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:40:34,717] {processor.py:153} INFO - Started process (PID=11260) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:40:34,722] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:40:34,723] {logging_mixin.py:115} INFO - [2023-07-08 11:40:34,723] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:40:34,772] {logging_mixin.py:115} INFO - [2023-07-08 11:40:34,771] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:40:34,773] {logging_mixin.py:115} INFO - [2023-07-08 11:40:34,773] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:40:34,773] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:40:34,803] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2023-07-08 11:41:17,022] {processor.py:153} INFO - Started process (PID=11653) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:17,026] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:41:17,028] {logging_mixin.py:115} INFO - [2023-07-08 11:41:17,027] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:17,061] {logging_mixin.py:115} INFO - [2023-07-08 11:41:17,060] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:41:17,061] {logging_mixin.py:115} INFO - [2023-07-08 11:41:17,061] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:41:17,061] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:17,081] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:41:55,690] {processor.py:153} INFO - Started process (PID=11770) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:55,691] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:41:55,692] {logging_mixin.py:115} INFO - [2023-07-08 11:41:55,692] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:55,728] {logging_mixin.py:115} INFO - [2023-07-08 11:41:55,727] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:41:55,728] {logging_mixin.py:115} INFO - [2023-07-08 11:41:55,728] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:41:55,729] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:41:55,749] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:42:32,953] {processor.py:153} INFO - Started process (PID=11938) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:42:32,956] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:42:32,957] {logging_mixin.py:115} INFO - [2023-07-08 11:42:32,957] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:42:32,990] {logging_mixin.py:115} INFO - [2023-07-08 11:42:32,989] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:42:32,991] {logging_mixin.py:115} INFO - [2023-07-08 11:42:32,991] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:42:32,991] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:42:33,011] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:43:11,300] {processor.py:153} INFO - Started process (PID=12241) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:11,303] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:43:11,304] {logging_mixin.py:115} INFO - [2023-07-08 11:43:11,304] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:11,342] {logging_mixin.py:115} INFO - [2023-07-08 11:43:11,341] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:43:11,343] {logging_mixin.py:115} INFO - [2023-07-08 11:43:11,342] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:43:11,343] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:11,359] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 11:43:47,645] {processor.py:153} INFO - Started process (PID=12317) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:47,647] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:43:47,648] {logging_mixin.py:115} INFO - [2023-07-08 11:43:47,647] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:47,681] {logging_mixin.py:115} INFO - [2023-07-08 11:43:47,680] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:43:47,681] {logging_mixin.py:115} INFO - [2023-07-08 11:43:47,681] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:43:47,681] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:43:47,702] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 11:44:25,509] {processor.py:153} INFO - Started process (PID=12378) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:44:25,513] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:44:25,514] {logging_mixin.py:115} INFO - [2023-07-08 11:44:25,514] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:44:25,547] {logging_mixin.py:115} INFO - [2023-07-08 11:44:25,546] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:44:25,547] {logging_mixin.py:115} INFO - [2023-07-08 11:44:25,547] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:44:25,547] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:44:25,567] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 11:45:05,744] {processor.py:153} INFO - Started process (PID=12451) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:05,746] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:45:05,747] {logging_mixin.py:115} INFO - [2023-07-08 11:45:05,747] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:05,789] {logging_mixin.py:115} INFO - [2023-07-08 11:45:05,788] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:45:05,789] {logging_mixin.py:115} INFO - [2023-07-08 11:45:05,789] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:45:05,789] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:05,813] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2023-07-08 11:45:40,775] {processor.py:153} INFO - Started process (PID=12562) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:40,778] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:45:40,779] {logging_mixin.py:115} INFO - [2023-07-08 11:45:40,779] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:40,790] {logging_mixin.py:115} INFO - [2023-07-08 11:45:40,790] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:45:40,790] {logging_mixin.py:115} INFO - [2023-07-08 11:45:40,790] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:45:40,790] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:45:40,796] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2023-07-08 11:46:20,249] {processor.py:153} INFO - Started process (PID=12776) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:20,253] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:46:20,254] {logging_mixin.py:115} INFO - [2023-07-08 11:46:20,254] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:20,287] {logging_mixin.py:115} INFO - [2023-07-08 11:46:20,286] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:46:20,287] {logging_mixin.py:115} INFO - [2023-07-08 11:46:20,287] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:46:20,288] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:20,305] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2023-07-08 11:46:55,675] {processor.py:153} INFO - Started process (PID=12822) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:55,678] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:46:55,680] {logging_mixin.py:115} INFO - [2023-07-08 11:46:55,679] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:55,713] {logging_mixin.py:115} INFO - [2023-07-08 11:46:55,712] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:46:55,713] {logging_mixin.py:115} INFO - [2023-07-08 11:46:55,713] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:46:55,714] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:46:55,733] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:47:32,487] {processor.py:153} INFO - Started process (PID=12868) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:47:32,488] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:47:32,490] {logging_mixin.py:115} INFO - [2023-07-08 11:47:32,489] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:47:32,523] {logging_mixin.py:115} INFO - [2023-07-08 11:47:32,522] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:47:32,523] {logging_mixin.py:115} INFO - [2023-07-08 11:47:32,523] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:47:32,523] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:47:32,543] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2023-07-08 11:48:07,959] {processor.py:153} INFO - Started process (PID=12941) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:07,963] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:48:07,964] {logging_mixin.py:115} INFO - [2023-07-08 11:48:07,964] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:07,997] {logging_mixin.py:115} INFO - [2023-07-08 11:48:07,996] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:48:07,998] {logging_mixin.py:115} INFO - [2023-07-08 11:48:07,998] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:48:07,998] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:08,018] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:48:47,299] {processor.py:153} INFO - Started process (PID=13009) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:47,303] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:48:47,304] {logging_mixin.py:115} INFO - [2023-07-08 11:48:47,304] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:47,339] {logging_mixin.py:115} INFO - [2023-07-08 11:48:47,339] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:48:47,340] {logging_mixin.py:115} INFO - [2023-07-08 11:48:47,340] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:48:47,340] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:48:47,360] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2023-07-08 11:49:25,694] {processor.py:153} INFO - Started process (PID=13075) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:49:25,694] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:49:25,695] {logging_mixin.py:115} INFO - [2023-07-08 11:49:25,695] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:49:25,705] {logging_mixin.py:115} INFO - [2023-07-08 11:49:25,705] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:49:25,705] {logging_mixin.py:115} INFO - [2023-07-08 11:49:25,705] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:49:25,706] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:49:25,712] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2023-07-08 11:50:02,068] {processor.py:153} INFO - Started process (PID=13123) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:02,072] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:50:02,073] {logging_mixin.py:115} INFO - [2023-07-08 11:50:02,072] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:02,107] {logging_mixin.py:115} INFO - [2023-07-08 11:50:02,106] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:50:02,107] {logging_mixin.py:115} INFO - [2023-07-08 11:50:02,107] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:50:02,107] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:02,128] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
[2023-07-08 11:50:43,278] {processor.py:153} INFO - Started process (PID=13266) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:43,281] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:50:43,283] {logging_mixin.py:115} INFO - [2023-07-08 11:50:43,282] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:43,316] {logging_mixin.py:115} INFO - [2023-07-08 11:50:43,316] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:50:43,317] {logging_mixin.py:115} INFO - [2023-07-08 11:50:43,317] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:50:43,317] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:50:43,336] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2023-07-08 11:51:23,665] {processor.py:153} INFO - Started process (PID=13322) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:51:23,669] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:51:23,670] {logging_mixin.py:115} INFO - [2023-07-08 11:51:23,670] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:51:23,704] {logging_mixin.py:115} INFO - [2023-07-08 11:51:23,703] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:51:23,704] {logging_mixin.py:115} INFO - [2023-07-08 11:51:23,704] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:51:23,704] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:51:23,722] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
[2023-07-08 11:52:00,713] {processor.py:153} INFO - Started process (PID=13366) to work on /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:52:00,717] {processor.py:641} INFO - Processing file /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-07-08 11:52:00,718] {logging_mixin.py:115} INFO - [2023-07-08 11:52:00,718] {dagbag.py:507} INFO - Filling up the DagBag from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:52:00,752] {logging_mixin.py:115} INFO - [2023-07-08 11:52:00,751] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-07-08 11:52:00,753] {logging_mixin.py:115} INFO - [2023-07-08 11:52:00,753] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-07-08 11:52:00,753] {processor.py:653} WARNING - No viable dags retrieved from /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-07-08 11:52:00,772] {processor.py:161} INFO - Processing /home/lucas/Área de Trabalho/apresentação/venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.065 seconds
