[2023-07-08 01:05:52,142] {taskinstance.py:1149} INFO - Dependencies not met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2023-07-08 01:05:52,143] {local_task_job.py:101} INFO - Task is not able to be run
